export type ToolStatus = 'available' | 'beta' | 'coming-soon';

export interface ToolMetadata {
  slug: string; // e.g. 'mouse-tester'
  name: string;
  shortDescription: string;
  category: string; // matches ToolCategory.id
  icon: string;
  status: ToolStatus;
  featured?: boolean;
  popular?: boolean;
  relatedTools?: string[]; // array of slugs
  seoTitle: string;
  seoDescription: string;
  keywords?: string[];
  lastUpdated?: string;
}

export const TOOLS_REGISTRY: ToolMetadata[] = [
  // ==========================================
  // Mouse & Input Tools (LIVE PRODUCTION)
  // ==========================================
  {
    slug: 'mouse-tester',
    name: 'Mouse Tester',
    shortDescription: 'Complete hardware diagnostic tool for buttons, scroll wheel, movement tracking, and event logs.',
    category: 'mouse-input',
    icon: '🖱️',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['mouse-click-test', 'double-click-test', 'mouse-polling-rate-test', 'mouse-scroll-test', 'cps-test'],
    seoTitle: 'Mouse Tester Online — Free Mouse Test | VEYLO',
    seoDescription: 'Free online mouse tester by VEYLO. Test your mouse buttons, clicks, scroll wheel, movement, and double-click behavior directly in your browser.',
    keywords: ['mouse tester', 'mouse test online', 'mouse button test', 'mouse hardware diagnostics'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'mouse-click-test',
    name: 'Mouse Click Test',
    shortDescription: 'Verify left, right, middle wheel, and side thumb button click signal transmission.',
    category: 'mouse-input',
    icon: '🎯',
    status: 'available',
    popular: true,
    relatedTools: ['mouse-tester', 'double-click-test', 'cps-test'],
    seoTitle: 'Mouse Click Test — Free Online Tool | VEYLO',
    seoDescription: 'Test your left click, right click, middle click, and side buttons for instant signal detection with VEYLO.',
    keywords: ['mouse click test', 'mouse button test', 'left click test', 'right click test'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'double-click-test',
    name: 'Double Click Test',
    shortDescription: 'Detect microswitch chatter and measure precise click interval timing in milliseconds.',
    category: 'mouse-input',
    icon: '⚡',
    status: 'available',
    popular: true,
    relatedTools: ['mouse-tester', 'mouse-click-test', 'cps-test'],
    seoTitle: 'Double Click Test — Free Online Tool | VEYLO',
    seoDescription: 'Test your mouse for accidental double clicks and microswitch chatter. Measures click interval timing in milliseconds.',
    keywords: ['double click test', 'mouse switch chatter', 'double clicking bug', 'switch chatter test'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'mouse-scroll-test',
    name: 'Mouse Scroll Test',
    shortDescription: 'Test scroll wheel notches, direction tracking (up/down/tilt), and middle button switch.',
    category: 'mouse-input',
    icon: '📜',
    status: 'available',
    relatedTools: ['mouse-tester', 'mouse-click-test'],
    seoTitle: 'Mouse Scroll Test — Free Online Tool | VEYLO',
    seoDescription: 'Test your mouse scroll wheel for smooth scrolling, notch detection, scroll direction, and middle click responsiveness with VEYLO.',
    keywords: ['mouse scroll test', 'scroll wheel test', 'mouse wheel tester', 'smooth scroll test'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'mouse-polling-rate-test',
    name: 'Mouse Polling Rate Test',
    shortDescription: 'Measure real-time mouse report frequency (Hz), peak rate, and interval latency.',
    category: 'mouse-input',
    icon: '📡',
    status: 'available',
    popular: true,
    relatedTools: ['mouse-tester', 'mouse-dpi-test', 'cps-test'],
    seoTitle: 'Mouse Polling Rate Test — Free Online Tool | VEYLO',
    seoDescription: 'Test your mouse polling rate (Hz) and report frequency online with VEYLO. Measure peak Hz and interval latency in milliseconds.',
    keywords: ['mouse polling rate test', 'mouse hz test', '1000hz mouse test', 'report rate test'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'mouse-dpi-test',
    name: 'Mouse DPI & eDPI Calculator',
    shortDescription: 'Estimate hardware sensor DPI and calculate eDPI effective sensitivity across video games.',
    category: 'mouse-input',
    icon: '📐',
    status: 'available',
    relatedTools: ['mouse-tester', 'mouse-polling-rate-test'],
    seoTitle: 'Mouse DPI Test & eDPI Calculator — Free Online Tool | VEYLO',
    seoDescription: 'Test your mouse DPI (Dots Per Inch) and calculate eDPI (Effective DPI) with VEYLO. Measure target mousepad distance against screen pixel movement.',
    keywords: ['mouse dpi test', 'mouse dpi calculator', 'edpi calculator', 'mouse sensitivity test'],
    lastUpdated: '2026-08-23',
  },
  {
    slug: 'cps-test',
    name: 'CPS Click Speed Test',
    shortDescription: 'Measure your Clicks Per Second across 1s to 60s challenges with live speed ranking.',
    category: 'mouse-input',
    icon: '⏱️',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['mouse-tester', 'mouse-click-test', 'double-click-test'],
    seoTitle: 'CPS Test — Free Online Click Speed Tool | VEYLO',
    seoDescription: 'Free CPS test (Click Speed Test) by VEYLO. Measure how many clicks per second you can achieve in 1s, 5s, 10s, 30s, or 60s challenges.',
    keywords: ['cps test', 'click speed test', 'clicks per second', 'jitter click test'],
    lastUpdated: '2026-08-23',
  },

  // ==========================================
  // 10 New Live Production Tools (Batch 1)
  // ==========================================
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    shortDescription: 'Generate random numbers within custom ranges with sorting, duplicate control, and batch copying.',
    category: 'random',
    icon: '🔢',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['dice-roller', 'coin-flip', 'random-choice-picker', 'yes-or-no'],
    seoTitle: 'Random Number Generator — Free Online Tool | VEYLO',
    seoDescription: 'Generate true random numbers online with custom min/max ranges, multiple quantity outputs, and sorting options. 100% client-side.',
    keywords: ['random number generator', 'rng online', 'random number picker', 'number randomizer', 'generate random numbers'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'random-word-generator',
    name: 'Random Word Generator',
    shortDescription: 'Generate random English words filtered by length, complexity, and parts of speech for creative writing.',
    category: 'writing',
    icon: '📖',
    status: 'available',
    popular: true,
    relatedTools: ['username-generator', 'random-letter-generator', 'truth-or-dare'],
    seoTitle: 'Random Word Generator — Free Online Tool | VEYLO',
    seoDescription: 'Generate random words with customizable word counts, length filters, and parts of speech for brainstorming and games.',
    keywords: ['random word generator', 'random words', 'word randomizer', 'generate words online', 'creative writing prompts'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'username-generator',
    name: 'Username Generator',
    shortDescription: 'Generate unique, creative usernames and gamer handles across gaming, tech, and aesthetic styles.',
    category: 'creativity',
    icon: '✨',
    status: 'available',
    popular: true,
    relatedTools: ['random-word-generator', 'random-letter-generator'],
    seoTitle: 'Username Generator — Free Online Gamertag & Handle Creator | VEYLO',
    seoDescription: 'Generate cool, unique usernames and gamer handles by style, keyword prefix, numbers, and separators with one-click copy.',
    keywords: ['username generator', 'gamertag generator', 'cool usernames', 'handle generator', 'online nickname maker'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'random-letter-generator',
    name: 'Random Letter Generator',
    shortDescription: 'Pick random letters from custom alphabets with uppercase, lowercase, and vowel/consonant filters.',
    category: 'random',
    icon: '🔤',
    status: 'available',
    relatedTools: ['random-number-generator', 'random-word-generator', 'dice-roller'],
    seoTitle: 'Random Letter Generator — Free Alphabet Picker | VEYLO',
    seoDescription: 'Generate random letters online. Choose alphabet sets, uppercase/lowercase, vowels or consonants, and batch quantities.',
    keywords: ['random letter generator', 'random alphabet generator', 'letter picker', 'random character generator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'coin-flip',
    name: 'Coin Flip Simulator',
    shortDescription: 'Flip virtual 3D coins with realistic animations, batch tosses, and live probability statistics.',
    category: 'random',
    icon: '🪙',
    status: 'available',
    popular: true,
    relatedTools: ['dice-roller', 'yes-or-no', 'random-choice-picker'],
    seoTitle: 'Coin Flip Online — 3D Coin Toss Simulator & Stats | VEYLO',
    seoDescription: 'Flip a coin online with realistic animations and live Heads/Tails statistics. Flip 1, 3, 5, or multiple coins at once.',
    keywords: ['coin flip', 'flip a coin online', 'heads or tails', 'virtual coin toss', 'coin flipper simulator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'dice-roller',
    name: 'Dice Roller (D4 - D100)',
    shortDescription: 'Roll virtual tabletop RPG dice (d4, d6, d8, d10, d12, d20, d100) with modifiers and roll history.',
    category: 'gaming',
    icon: '🎲',
    status: 'available',
    popular: true,
    relatedTools: ['coin-flip', 'random-number-generator', 'random-choice-picker'],
    seoTitle: 'Dice Roller Online — D&D & RPG Multi-Dice Simulator | VEYLO',
    seoDescription: 'Virtual dice roller for tabletop RPGs and board games. Roll d4, d6, d8, d10, d12, d20, and d100 dice with custom modifiers.',
    keywords: ['dice roller', 'dnd dice roller', 'd20 roller', 'roll dice online', 'tabletop dice simulator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'yes-or-no',
    name: 'Yes or No Wheel & Generator',
    shortDescription: 'Instant decision maker with dynamic reveal animations, weighted odds, and custom questions.',
    category: 'random',
    icon: '🔮',
    status: 'available',
    popular: true,
    relatedTools: ['coin-flip', 'random-choice-picker', 'truth-or-dare'],
    seoTitle: 'Yes or No Generator — Instant Decision Maker | VEYLO',
    seoDescription: 'Get an instant, unbiased Yes or No answer to any question with dynamic reveal animations and decision tracking.',
    keywords: ['yes or no generator', 'yes or no wheel', 'decision maker online', 'random yes no picker'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'random-choice-picker',
    name: 'Random Choice Picker',
    shortDescription: 'Paste your list of options to randomly pick a winner with elimination mode and raffle animations.',
    category: 'random',
    icon: '🎯',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['team-generator', 'yes-or-no', 'random-number-generator'],
    seoTitle: 'Random Choice Picker — Pick a Random Item from List | VEYLO',
    seoDescription: 'Randomly select one or multiple winners from any list of items. Features elimination raffle mode and preset templates.',
    keywords: ['random choice picker', 'random selector', 'pick from list', 'random name picker', 'raffle picker'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'team-generator',
    name: 'Random Team Generator',
    shortDescription: 'Evenly balance and randomly divide names into balanced teams or fixed group sizes.',
    category: 'productivity',
    icon: '👥',
    status: 'available',
    popular: true,
    relatedTools: ['random-choice-picker', 'random-number-generator'],
    seoTitle: 'Random Team Generator — Divide Names into Balanced Groups | VEYLO',
    seoDescription: 'Quickly split a list of player or student names into fair, randomized teams. Choose number of teams or team size.',
    keywords: ['team generator', 'random team generator', 'group maker', 'split into teams', 'balanced team picker'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'truth-or-dare',
    name: 'Truth or Dare Generator',
    shortDescription: 'Hundreds of fun, clean party prompts for friends, family game nights, and icebreakers.',
    category: 'creativity',
    icon: '🎭',
    status: 'available',
    popular: true,
    relatedTools: ['yes-or-no', 'random-choice-picker', 'random-word-generator'],
    seoTitle: 'Truth or Dare Generator — Fun Party Game Prompts | VEYLO',
    seoDescription: 'Play Truth or Dare online with hundreds of curated, family-safe questions and fun dares categorized by party vibe.',
    keywords: ['truth or dare generator', 'truth or dare questions', 'party game prompts', 'truth or dare online'],
    lastUpdated: '2026-08-25',
  },

  // ==========================================
  // Batch 2: Creativity & Ideas Tools (LIVE PRODUCTION)
  // ==========================================
  {
    slug: 'random-idea-generator',
    name: 'Random Idea Generator',
    shortDescription: 'Generate creative concept ideas for startup businesses, software apps, YouTube content, and personal projects.',
    category: 'creativity',
    icon: '💡',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['story-idea-generator', 'character-generator', 'username-generator'],
    seoTitle: 'Random Idea Generator — Business, App & Project Concepts | VEYLO',
    seoDescription: 'Generate creative ideas for startups, web apps, content creation, and personal projects with structured hooks and target niches.',
    keywords: ['random idea generator', 'business idea generator', 'app idea generator', 'creative project ideas', 'brainstorming tool'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'story-idea-generator',
    name: 'Story Idea Generator',
    shortDescription: 'Create engaging fiction story premises with genre, protagonist, setting, core conflict, and unexpected plot twists.',
    category: 'writing',
    icon: '📚',
    status: 'available',
    popular: true,
    relatedTools: ['plot-generator', 'character-generator', 'random-word-generator'],
    seoTitle: 'Story Idea Generator — Creative Writing Prompts & Premise Creator | VEYLO',
    seoDescription: 'Generate story concepts for novels, screenplays, and short fiction with customizable genres, protagonists, and dramatic twists.',
    keywords: ['story idea generator', 'writing prompts', 'story premise generator', 'creative writing generator', 'plot hook generator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'character-generator',
    name: 'Character Generator',
    shortDescription: 'Build fictional characters with personality traits, occupations, motivations, flaws, and hidden secrets.',
    category: 'writing',
    icon: '👤',
    status: 'available',
    popular: true,
    relatedTools: ['character-name-generator', 'story-idea-generator', 'plot-generator'],
    seoTitle: 'Character Generator — Fictional Persona & NPC Creator | VEYLO',
    seoDescription: 'Generate fleshed-out characters with unique personalities, flaws, goals, occupations, and backstories for fiction and tabletop RPGs.',
    keywords: ['character generator', 'npc generator', 'character creator', 'fictional persona maker', 'rpg character traits'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'plot-generator',
    name: 'Plot Generator',
    shortDescription: 'Generate three-act narrative plot frameworks with inciting incidents, midpoint shifts, and dramatic climaxes.',
    category: 'writing',
    icon: '🗺️',
    status: 'available',
    popular: true,
    relatedTools: ['story-idea-generator', 'character-generator', 'art-prompt-generator'],
    seoTitle: 'Plot Generator — Three-Act Story & Narrative Outline Creator | VEYLO',
    seoDescription: 'Generate three-act narrative plot structures complete with inciting incidents, rising conflicts, midpoint shifts, and climaxes.',
    keywords: ['plot generator', 'story outline generator', 'narrative structure', 'novel plot creator', 'creative writing outline'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'song-idea-generator',
    name: 'Song Idea Generator',
    shortDescription: 'Generate musical concepts with genre, emotional mood, tempo (BPM), instrumentation, and hook concepts.',
    category: 'creativity',
    icon: '🎵',
    status: 'available',
    popular: true,
    relatedTools: ['music-genre-generator', 'band-name-generator'],
    seoTitle: 'Song Idea Generator — Music Songwriting Prompts & Hooks | VEYLO',
    seoDescription: 'Generate original song concepts with genre, BPM, mood, instrumentation arrangements, and hook themes for songwriters.',
    keywords: ['song idea generator', 'songwriting prompts', 'music idea generator', 'lyric theme ideas', 'chord progression concept'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'music-genre-generator',
    name: 'Music Genre Generator',
    shortDescription: 'Create hybrid music genres and fusion subgenres with tempo guidelines and signature sonic elements.',
    category: 'creativity',
    icon: '🎧',
    status: 'available',
    relatedTools: ['song-idea-generator', 'band-name-generator'],
    seoTitle: 'Music Genre Generator — Fusion Subgenre & Style Creator | VEYLO',
    seoDescription: 'Discover fresh musical fusion genres and experimental subgenres with instrumentation tips and stylistic rhythm profiles.',
    keywords: ['music genre generator', 'fusion genre maker', 'random music styles', 'subgenre creator', 'music production inspiration'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'band-name-generator',
    name: 'Band Name Generator',
    shortDescription: 'Generate cool, memorable band names and artist aliases across rock, indie, electronic, metal, and lo-fi styles.',
    category: 'creativity',
    icon: '🎸',
    status: 'available',
    popular: true,
    relatedTools: ['song-idea-generator', 'username-generator'],
    seoTitle: 'Band Name Generator — Creative Artist & Band Name Maker | VEYLO',
    seoDescription: 'Generate catchy band names and music artist aliases filtered by style: rock, indie, electronic, synthwave, metal, and lo-fi.',
    keywords: ['band name generator', 'music artist names', 'rock band names', 'dj name generator', 'indie band name maker'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'art-prompt-generator',
    name: 'Art Prompt Generator',
    shortDescription: 'Generate rich visual art prompts with subject matter, environment, lighting, composition, and color palette concepts.',
    category: 'creativity',
    icon: '🎨',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['drawing-prompt-generator', 'character-generator', 'story-idea-generator'],
    seoTitle: 'Art Prompt Generator — Visual Concept & Illustration Prompts | VEYLO',
    seoDescription: 'Generate rich art prompts with lighting, mood, color palette suggestions, and compositional framing for digital and traditional artists.',
    keywords: ['art prompt generator', 'illustration ideas', 'digital painting prompts', 'concept art generator', 'creative drawing ideas'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'drawing-prompt-generator',
    name: 'Drawing Prompt Generator',
    shortDescription: 'Quick sketch challenges and daily drawing prompts with difficulty filters and optional warmup timer.',
    category: 'creativity',
    icon: '✏️',
    status: 'available',
    popular: true,
    relatedTools: ['art-prompt-generator', 'character-generator'],
    seoTitle: 'Drawing Prompt Generator — Daily Sketch Challenges & Ideas | VEYLO',
    seoDescription: 'Instant drawing prompts for daily sketchbook practice. Features difficulty levels from quick warmups to complex character challenges.',
    keywords: ['drawing prompt generator', 'sketchbook prompts', 'daily drawing challenge', 'quick sketch ideas', 'drawing warmup generator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'character-name-generator',
    name: 'Character Name Generator',
    shortDescription: 'Generate authentic character names across fantasy, sci-fi, modern, historical, and mythological genres.',
    category: 'writing',
    icon: '🏷️',
    status: 'available',
    popular: true,
    relatedTools: ['character-generator', 'username-generator', 'story-idea-generator'],
    seoTitle: 'Character Name Generator — Fantasy, Sci-Fi & Modern Names | VEYLO',
    seoDescription: 'Generate distinctive character first names, surnames, and titles across fantasy, cyberpunk, sci-fi, medieval, and modern genres.',
    keywords: ['character name generator', 'fantasy name generator', 'sci fi names', 'novel character names', 'rpg name maker'],
    lastUpdated: '2026-08-25',
  },

  // ==========================================
  // Batch 3: Text Utilities Tools (LIVE PRODUCTION)
  // ==========================================
  {
    slug: 'word-counter',
    name: 'Word & Text Statistics Counter',
    shortDescription: 'Count words, characters, sentences, paragraphs, and estimate reading/speaking times in real time.',
    category: 'text',
    icon: '📊',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['character-counter', 'sentence-counter', 'case-converter'],
    seoTitle: 'Word Counter — Real-Time Word & Character Counter | VEYLO',
    seoDescription: 'Free online word counter and text statistics analyzer. Measures words, characters with/without spaces, sentences, paragraphs, and reading time.',
    keywords: ['word counter', 'character counter', 'word count online', 'text length checker', 'reading time calculator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'character-counter',
    name: 'Character Counter & Social Limits',
    shortDescription: 'Precise character count with Twitter/X, Instagram, SMS, and SEO meta description limits.',
    category: 'text',
    icon: '🔤',
    status: 'available',
    popular: true,
    relatedTools: ['word-counter', 'sentence-counter', 'case-converter'],
    seoTitle: 'Character Counter — Online Letter & Character Checker | VEYLO',
    seoDescription: 'Count characters, letters, digits, and spaces in real-time. Includes social media character limit indicators for Twitter, Instagram, and SEO.',
    keywords: ['character counter', 'letter counter', 'character count tool', 'twitter character counter', 'social media text limit'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'sentence-counter',
    name: 'Sentence Counter & Readability',
    shortDescription: 'Count sentences, compute average sentence length, and evaluate text readability metrics.',
    category: 'writing',
    icon: '📑',
    status: 'available',
    relatedTools: ['word-counter', 'character-counter', 'text-cleaner'],
    seoTitle: 'Sentence Counter — Count Sentences & Readability Analyzer | VEYLO',
    seoDescription: 'Count sentences in any text, compute average words per sentence, and analyze readability scores for essays and copy.',
    keywords: ['sentence counter', 'count sentences', 'readability checker', 'average sentence length', 'text analyzer'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'case-converter',
    name: 'Text Case Converter',
    shortDescription: 'Convert text between UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, and kebab-case.',
    category: 'text',
    icon: '🔄',
    status: 'available',
    popular: true,
    relatedTools: ['text-cleaner', 'word-counter', 'text-reverser'],
    seoTitle: 'Text Case Converter — Uppercase, Lowercase, Title Case | VEYLO',
    seoDescription: 'Convert text case instantly: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case, and PascalCase.',
    keywords: ['case converter', 'uppercase converter', 'lowercase to uppercase', 'title case converter', 'camelcase generator', 'snake case converter'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'text-reverser',
    name: 'Text Reverser & Inverter',
    shortDescription: 'Reverse entire text, invert word order, reverse letters per word, or flip text upside down.',
    category: 'text',
    icon: '🔁',
    status: 'available',
    relatedTools: ['case-converter', 'text-cleaner', 'sort-lines'],
    seoTitle: 'Text Reverser — Reverse Text, Words, & Upside Down Flipper | VEYLO',
    seoDescription: 'Reverse text backwards, invert word order, flip letters in place, or generate upside-down Unicode text online.',
    keywords: ['text reverser', 'reverse text online', 'backwards text generator', 'reverse words', 'upside down text generator'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    shortDescription: 'Delete duplicate lines from lists and code with case sensitivity and trimming options.',
    category: 'text',
    icon: '🧹',
    status: 'available',
    popular: true,
    relatedTools: ['sort-lines', 'text-cleaner', 'text-diff-checker'],
    seoTitle: 'Remove Duplicate Lines — Deduplicate Lists & Text Online | VEYLO',
    seoDescription: 'Quickly remove duplicate lines from lists, data sets, and text files. Supports case-sensitivity, whitespace trimming, and line sorting.',
    keywords: ['remove duplicate lines', 'deduplicate list', 'duplicate line remover', 'unique lines extractor', 'clean list online'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'sort-lines',
    name: 'Sort Lines (Alphabetical & Numeric)',
    shortDescription: 'Sort text lines alphabetically (A-Z, Z-A), numerically, by length, or random shuffle.',
    category: 'text',
    icon: '🔀',
    status: 'available',
    popular: true,
    relatedTools: ['remove-duplicate-lines', 'text-cleaner', 'case-converter'],
    seoTitle: 'Sort Lines Online — Alphabetical, Numeric & Length Sorter | VEYLO',
    seoDescription: 'Sort lines of text alphabetically (A-Z, Z-A), numerically (1-9, 9-1), by character length, or randomize order.',
    keywords: ['sort lines', 'alphabetize text', 'sort lines alphabetically', 'numeric line sorter', 'list alphabetizer'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Placeholder Generator',
    shortDescription: 'Generate classic Latin dummy placeholder text by paragraphs, sentences, or word counts.',
    category: 'generators',
    icon: '📄',
    status: 'available',
    popular: true,
    relatedTools: ['word-counter', 'random-word-generator'],
    seoTitle: 'Lorem Ipsum Generator — Free Placeholder Dummy Text | VEYLO',
    seoDescription: 'Generate dummy Lorem Ipsum placeholder text for web design, layouts, and typography. Customize by paragraphs, sentences, or word count.',
    keywords: ['lorem ipsum generator', 'dummy text generator', 'placeholder text', 'latin text generator', 'lorem ipsum paragraphs'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'text-cleaner',
    name: 'Text Cleaner & Whitespace Remover',
    shortDescription: 'Trim whitespace, remove blank lines, strip extra spaces, remove HTML tags, and normalize line breaks.',
    category: 'text',
    icon: '🧼',
    status: 'available',
    popular: true,
    relatedTools: ['remove-duplicate-lines', 'case-converter', 'word-counter'],
    seoTitle: 'Text Cleaner — Remove Extra Spaces, Blank Lines & HTML | VEYLO',
    seoDescription: 'Clean and format messy text online. Strip duplicate whitespace, remove blank lines, sanitize line endings, and strip HTML tags.',
    keywords: ['text cleaner', 'remove extra spaces', 'remove blank lines', 'strip html tags', 'whitespace remover online'],
    lastUpdated: '2026-08-25',
  },
  {
    slug: 'text-diff-checker',
    name: 'Text Diff Checker & Comparison',
    shortDescription: 'Compare two text blocks side-by-side or inline with visual highlighting of additions, deletions, and edits.',
    category: 'developer',
    icon: '⚖️',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['text-cleaner', 'remove-duplicate-lines', 'case-converter'],
    seoTitle: 'Text Diff Checker — Compare Text & Find Differences Online | VEYLO',
    seoDescription: 'Compare two text files or snippets side-by-side to highlight added, removed, and modified lines with precise visual diffing.',
    keywords: ['text diff checker', 'diff checker online', 'compare text', 'text difference finder', 'file comparison tool'],
    lastUpdated: '2026-08-25',
  },

  // ==========================================
  // 17 Production Expansion Tools (LIVE)
  // ==========================================
  {
    slug: 'password-generator',
    name: 'Secure Password Generator',
    shortDescription: 'Generate strong, cryptographic passwords client-side with custom length, character sets, and entropy estimation.',
    category: 'generators',
    icon: '🔑',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['uuid-generator', 'hash-generator', 'base64'],
    seoTitle: 'Secure Password Generator — Free Cryptographic Generator | VEYLO',
    seoDescription: 'Generate strong, random passwords securely in your browser using the Web Crypto API. Customize length, uppercase, numbers, symbols, and batch generation.',
    keywords: ['password generator', 'secure password generator', 'random password generator', 'strong password maker', 'cryptographic password generator'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    shortDescription: 'Generate RFC 4122 compliant version 4 UUIDs with bulk generation, casing options, and instant copying.',
    category: 'generators',
    icon: '🆔',
    status: 'available',
    popular: true,
    relatedTools: ['password-generator', 'hash-generator', 'base64'],
    seoTitle: 'UUID Generator — Free Online UUID v4 & GUID Generator | VEYLO',
    seoDescription: 'Generate RFC 4122 compliant UUID v4 identifiers in bulk. Customize uppercase/lowercase, hyphens, and braces with one-click copy.',
    keywords: ['uuid generator', 'guid generator', 'uuid v4 generator', 'bulk uuid generator', 'random uuid maker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    shortDescription: 'Create custom QR codes for URLs, text, Wi-Fi networks, and contact cards with color options and SVG/PNG download.',
    category: 'generators',
    icon: '📱',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['password-generator', 'base64', 'color-converter'],
    seoTitle: 'QR Code Generator — Free Custom QR Code Creator | VEYLO',
    seoDescription: 'Create custom QR codes for URLs, text, Wi-Fi, and contacts with custom colors, error correction, and instant PNG/SVG download. 100% client-side.',
    keywords: ['qr code generator', 'free qr code maker', 'custom qr code', 'wifi qr code generator', 'download qr code'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator (SHA-256, SHA-512, MD5, HMAC)',
    shortDescription: 'Generate cryptographic hashes for text and files using SHA-256, SHA-384, SHA-512, MD5, and HMAC.',
    category: 'developer',
    icon: '🔒',
    status: 'available',
    popular: true,
    relatedTools: ['password-generator', 'uuid-generator', 'base64', 'json-formatter'],
    seoTitle: 'Hash Generator — Free SHA-256, SHA-512, MD5 & HMAC Calculator | VEYLO',
    seoDescription: 'Calculate cryptographic hashes client-side with Web Crypto API. Supports SHA-256, SHA-384, SHA-512, MD5, and HMAC for strings and local files.',
    keywords: ['hash generator', 'sha256 generator', 'sha512 calculator', 'md5 hash generator', 'hmac generator', 'file hash checker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Beautify, minify, validate, and inspect JSON tree hierarchy with syntax error reporting.',
    category: 'developer',
    icon: '🔧',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['regex-tester', 'base64', 'text-diff-checker', 'text-case-converter'],
    seoTitle: 'JSON Formatter & Validator — Beautify, Minify & Inspect JSON | VEYLO',
    seoDescription: 'Format, validate, beautify, and minify JSON data client-side with syntax error highlighting, collapsible tree inspector, and instant copy.',
    keywords: ['json formatter', 'json beautifier', 'json validator', 'minify json', 'json tree viewer', 'json parser online'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester & Matcher',
    shortDescription: 'Test regular expressions in real time with capture groups breakdown, flag toggles, and visual match highlighting.',
    category: 'developer',
    icon: '🔍',
    status: 'available',
    popular: true,
    relatedTools: ['json-formatter', 'text-diff-checker', 'text-case-converter', 'word-character-counter'],
    seoTitle: 'Regex Tester & Matcher — Real-Time Regular Expression Tool | VEYLO',
    seoDescription: 'Test JavaScript regular expressions live with match highlighting, capture groups, named groups, flag toggles, and pattern presets.',
    keywords: ['regex tester', 'regular expression tester', 'regex matcher', 'regex debugger', 'javascript regex tool'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'base64',
    name: 'Base64 Encoder & Decoder',
    shortDescription: 'Encode and decode UTF-8 text, URLs, and local files into Base64 format client-side with zero data uploads.',
    category: 'developer',
    icon: '📦',
    status: 'available',
    popular: true,
    relatedTools: ['hash-generator', 'json-formatter', 'uuid-generator', 'password-generator'],
    seoTitle: 'Base64 Encoder & Decoder — Free Online UTF-8 Base64 Tool | VEYLO',
    seoDescription: 'Encode and decode UTF-8 text, URLs, and files to and from Base64 format safely in your browser. Supports URL-safe encoding and image preview.',
    keywords: ['base64 encoder', 'base64 decoder', 'base64 converter', 'encode base64 online', 'utf8 base64'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'Calculate percentage increases, decreases, differences, discounts, and fractions with step-by-step formulas.',
    category: 'calculators',
    icon: '➗',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['aspect-ratio-calculator', 'data-converter', 'mouse-dpi-test'],
    seoTitle: 'Percentage Calculator — Free Online Percent Calculation Tool | VEYLO',
    seoDescription: 'Calculate percentage increase, percentage decrease, discounts, percentage difference, and fraction shares with instant formulas and step-by-step breakdown.',
    keywords: ['percentage calculator', 'percent increase calculator', 'discount calculator', 'percent difference', 'calculate percentage'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    shortDescription: 'Calculate dimensions, ratio fractions (16:9, 4:3, 21:9), scale resolutions, and resize images proportionally.',
    category: 'calculators',
    icon: '📐',
    status: 'available',
    popular: true,
    relatedTools: ['percentage-calculator', 'color-converter', 'dead-pixel-test'],
    seoTitle: 'Aspect Ratio Calculator — Image & Video Dimension Sizer | VEYLO',
    seoDescription: 'Calculate image and video aspect ratios, simplify fraction ratios, scale dimensions proportionally, and preview aspect ratios visually.',
    keywords: ['aspect ratio calculator', '16:9 calculator', 'image ratio sizer', 'resolution scaler', 'screen ratio calculator'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'color-converter',
    name: 'Color Code Converter (HEX, RGB, HSL, HSV, CMYK)',
    shortDescription: 'Convert between HEX, RGB, HSL, HSV, and CMYK color spaces with live preview and contrast checks.',
    category: 'converters',
    icon: '🎨',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['qr-code-generator', 'aspect-ratio-calculator', 'dead-pixel-test'],
    seoTitle: 'Color Converter — HEX, RGB, HSL, HSV & CMYK Converter | VEYLO',
    seoDescription: 'Convert color codes between HEX, RGB, HSL, HSV, and CMYK with live preview, WCAG contrast checks, and shade palette generation.',
    keywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hsl converter', 'cmyk color converter', 'color code picker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'data-converter',
    name: 'Data Storage & Bandwidth Converter',
    shortDescription: 'Convert Bytes, KB, MB, GB, TB, and calculate download/upload transfer times (MB/s vs Mbps).',
    category: 'converters',
    icon: '💾',
    status: 'available',
    popular: true,
    relatedTools: ['percentage-calculator', 'aspect-ratio-calculator', 'mouse-polling-rate-test'],
    seoTitle: 'Data Unit & Bandwidth Converter — Storage & Speed Calculator | VEYLO',
    seoDescription: 'Convert data storage units (Bytes, KB, MB, GB, TB in Decimal vs Binary) and network transfer bandwidth (Mbps vs MB/s) with download time estimator.',
    keywords: ['data converter', 'byte converter', 'mb to gb', 'bandwidth calculator', 'mbps to mbs', 'download time calculator'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    shortDescription: 'Transform text into UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case.',
    category: 'text',
    icon: '🔤',
    status: 'available',
    popular: true,
    relatedTools: ['word-character-counter', 'json-formatter', 'text-diff-checker', 'text-cleaner'],
    seoTitle: 'Text Case Converter — Uppercase, Title Case, camelCase | VEYLO',
    seoDescription: 'Convert text case instantly: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, and CONSTANT_CASE with live multi-card previews.',
    keywords: ['text case converter', 'uppercase converter', 'title case converter', 'camelcase converter', 'snake case converter', 'lowercase converter'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'word-character-counter',
    name: 'Word & Character Counter',
    shortDescription: 'Analyze word count, characters, sentences, paragraphs, reading time, speaking time, and social media limits.',
    category: 'writing',
    icon: '📊',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['text-case-converter', 'sentence-counter', 'character-counter', 'regex-tester'],
    seoTitle: 'Word & Character Counter — Real-Time Text Statistics | VEYLO',
    seoDescription: 'Real-time word counter, character counter, sentence counter, paragraph counter, reading/speaking time estimator, and social media character limits checker.',
    keywords: ['word counter', 'character counter', 'word count tool', 'text length checker', 'reading time calculator', 'sentence counter'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'gamepad-tester',
    name: 'Gamepad & Controller Tester',
    shortDescription: 'Test Xbox, PlayStation, Nintendo, and USB controllers with live button signals, analog stick axes, trigger pressure, and rumble.',
    category: 'gaming',
    icon: '🎮',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['mouse-tester', 'cps-test', 'refresh-rate-test'],
    seoTitle: 'Gamepad Tester — Free Online Game Controller Test | VEYLO',
    seoDescription: 'Test gamepad and game controllers online using HTML5 Gamepad API. Inspect button signals, trigger pressure, analog stick drift, and vibration rumble.',
    keywords: ['gamepad tester', 'controller tester', 'game controller test', 'joystick drift test', 'xbox controller test', 'ps5 controller test'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'dead-pixel-test',
    name: 'Dead Pixel Test',
    shortDescription: 'Fullscreen color canvas to detect stuck or dead LCD/OLED pixels across primary RGB and monochrome colors.',
    category: 'screen-display',
    icon: '🖥️',
    status: 'available',
    popular: true,
    relatedTools: ['refresh-rate-test', 'aspect-ratio-calculator', 'color-converter'],
    seoTitle: 'Dead Pixel Test — Free Fullscreen Screen Test | VEYLO',
    seoDescription: 'Check your monitor, laptop, or phone screen for dead or stuck pixels with full-screen solid RGB colors, monochrome backgrounds, and keyboard shortcuts.',
    keywords: ['dead pixel test', 'stuck pixel test', 'screen test online', 'monitor dead pixel check', 'pixel checker fullscreen'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'refresh-rate-test',
    name: 'Screen Refresh Rate (Hz) Test',
    shortDescription: 'Benchmark browser frame rate, measured FPS, and frame timing stability using high-precision requestAnimationFrame.',
    category: 'screen-display',
    icon: '⚡',
    status: 'available',
    popular: true,
    relatedTools: ['dead-pixel-test', 'mouse-polling-rate-test', 'gamepad-tester'],
    seoTitle: 'Screen Refresh Rate Test — Monitor Hz & Browser FPS Test | VEYLO',
    seoDescription: 'Measure your monitor display refresh rate (60Hz, 120Hz, 144Hz, 240Hz, 360Hz) and browser frame rate stability using high-precision frame timing.',
    keywords: ['refresh rate test', 'screen hz test', 'monitor hz test', 'fps test online', 'browser refresh rate checker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'stopwatch',
    name: 'Online Stopwatch & Lap Timer',
    shortDescription: 'High-precision browser stopwatch with split lap tracking, fastest/slowest lap highlights, hotkeys, and audio cues.',
    category: 'productivity',
    icon: '⏱️',
    status: 'available',
    popular: true,
    relatedTools: ['cps-test', 'mouse-tester', 'word-character-counter'],
    seoTitle: 'Online Stopwatch & Lap Timer — Millisecond Accurate Timer | VEYLO',
    seoDescription: 'Free online stopwatch with millisecond precision, split lap records, keyboard hotkeys, lap statistics, and CSV export. Immune to tab throttling.',
    keywords: ['online stopwatch', 'stopwatch with laps', 'lap timer', 'split timer', 'millisecond stopwatch', 'precision stopwatch'],
    lastUpdated: '2026-08-29',
  },
  // ==========================================
  // Developer Tools Cluster (LIVE PRODUCTION)
  // ==========================================
  {
    slug: 'tools/jwt-decoder',
    name: 'JWT Decoder & Inspector',
    shortDescription: 'Decode and inspect JSON Web Tokens (JWT) client-side. View decoded header, payload, timestamps, and signature.',
    category: 'developer',
    icon: '🔑',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['tools/jwt-generator', 'base64', 'json-formatter', 'hash-generator'],
    seoTitle: 'JWT Decoder & Token Inspector — Decode JSON Web Tokens Online | VEYLO',
    seoDescription: 'Free client-side JWT decoder. Inspect JSON Web Token header, claims payload, expiration status, and signature safely without server transmission.',
    keywords: ['jwt decoder', 'decode jwt', 'jwt token decoder', 'jwt inspector', 'jwt viewer online', 'json web token parser'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/url-encoder',
    name: 'URL Encoder & Decoder',
    shortDescription: 'Encode and decode URLs and URI components with full Unicode safety, special character handling, and instant copy.',
    category: 'developer',
    icon: '🔗',
    status: 'available',
    popular: true,
    relatedTools: ['tools/url-parser', 'tools/html-entities', 'base64'],
    seoTitle: 'URL Encoder & Decoder — Encode & Decode URI Components Online | VEYLO',
    seoDescription: 'Encode and decode URLs and URI query parameters client-side. Convert special characters and UTF-8 strings safely.',
    keywords: ['url encoder', 'url decoder', 'encode url', 'decode url', 'uri component encoder', 'percent encoding'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/url-parser',
    name: 'URL Parser & Query Inspector',
    shortDescription: 'Parse URLs into protocol, host, port, path, query parameters table, and hash fragment with parameter editing.',
    category: 'developer',
    icon: '🌐',
    status: 'available',
    popular: true,
    relatedTools: ['tools/url-encoder', 'tools/http-status-codes', 'tools/user-agent-parser'],
    seoTitle: 'URL Parser & Query String Analyzer — Break Down URLs Online | VEYLO',
    seoDescription: 'Break down complex URLs into protocol, domain, port, path, and query parameters using browser-native URL API.',
    keywords: ['url parser', 'parse url online', 'query string parser', 'url analyzer', 'query parameter decoder'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/http-status-codes',
    name: 'HTTP Status Code Reference & Checker',
    shortDescription: 'Searchable directory of HTTP 1xx–5xx status codes with official RFC specifications, common causes, and debugging tips.',
    category: 'developer',
    icon: '🚦',
    status: 'available',
    popular: true,
    relatedTools: ['tools/url-parser', 'tools/jwt-decoder', 'json-formatter'],
    seoTitle: 'HTTP Status Codes Directory & Quick Reference — 1xx to 5xx Codes | VEYLO',
    seoDescription: 'Search and inspect HTTP response status codes (100–599) with official RFC definitions, meaning, causes, and troubleshooting guides.',
    keywords: ['http status codes', 'http error codes', '404 status code', '500 internal server error', 'http response codes list'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/unix-timestamp',
    name: 'Unix Timestamp Converter',
    shortDescription: 'Convert Unix epoch timestamps to human-readable dates and back. Supports seconds, milliseconds, UTC, and local time.',
    category: 'developer',
    icon: '⌛',
    status: 'available',
    popular: true,
    relatedTools: ['tools/cron-generator', 'percentage-calculator', 'data-converter'],
    seoTitle: 'Unix Timestamp Converter — Epoch to Date & Date to Epoch | VEYLO',
    seoDescription: 'Convert Unix epoch timestamps to human-readable date strings and ISO 8601 format. Live epoch clock with seconds and milliseconds detection.',
    keywords: ['unix timestamp converter', 'epoch converter', 'unix time to date', 'timestamp to human readable', 'epoch timestamp'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/cron-generator',
    name: 'Cron Expression Generator & Explainer',
    shortDescription: 'Visual cron schedule builder and validator. Generate 5-part cron expressions with human-readable explanations and presets.',
    category: 'developer',
    icon: '⏰',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['tools/unix-timestamp', 'stopwatch', 'tools/diff-checker'],
    seoTitle: 'Cron Expression Generator & Schedule Explainer — Build Cron Jobs | VEYLO',
    seoDescription: 'Generate, validate, and understand cron expressions visually with natural language translations, presets, and standard 5-part syntax.',
    keywords: ['cron generator', 'cron expression generator', 'cron schedule builder', 'crontab generator', 'cron explainer'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/html-entities',
    name: 'HTML Entity Encoder & Decoder',
    shortDescription: 'Encode and decode HTML entities, special characters (&lt;, &gt;, &amp;, &quot;), numeric codes, and Unicode characters.',
    category: 'developer',
    icon: '🏷️',
    status: 'available',
    popular: true,
    relatedTools: ['tools/url-encoder', 'tools/markdown-preview', 'text-case-converter'],
    seoTitle: 'HTML Entity Encoder & Decoder — Encode & Decode Special Characters | VEYLO',
    seoDescription: 'Convert special characters to HTML entities and back. Supports named entities, decimal codes, hex numeric entities, and Unicode.',
    keywords: ['html entity encoder', 'html entity decoder', 'html entities', 'encode html entities', 'special characters html'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/xml-formatter',
    name: 'XML Formatter & Validator',
    shortDescription: 'Beautify, format, minify, and validate XML documents client-side with indentation control and syntax error detection.',
    category: 'developer',
    icon: '📄',
    status: 'available',
    popular: true,
    relatedTools: ['json-formatter', 'tools/json-yaml', 'tools/sql-formatter'],
    seoTitle: 'XML Formatter & Validator — Beautify & Minify XML Online | VEYLO',
    seoDescription: 'Format, beautify, indent, and validate XML documents in your browser. Features DOMParser syntax error highlighting and minification.',
    keywords: ['xml formatter', 'xml beautifier', 'xml validator', 'format xml online', 'xml minifier', 'prettify xml'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/sql-formatter',
    name: 'SQL Formatter & Beautifier',
    shortDescription: 'Format and beautify SQL queries with standardized keyword capitalization, indentation, and minification.',
    category: 'developer',
    icon: '🗄️',
    status: 'available',
    popular: true,
    relatedTools: ['json-formatter', 'tools/xml-formatter', 'tools/json-yaml'],
    seoTitle: 'SQL Formatter & Query Beautifier — Clean & Indent SQL Online | VEYLO',
    seoDescription: 'Beautify and format messy SQL queries client-side with keyword capitalization, custom indentation, and minification. 100% private.',
    keywords: ['sql formatter', 'sql beautifier', 'format sql online', 'sql query formatter', 'prettify sql'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/markdown-preview',
    name: 'Markdown Live Previewer & Editor',
    shortDescription: 'Interactive split-pane Markdown editor with real-time GitHub-flavored Markdown rendering and strict XSS sanitization.',
    category: 'developer',
    icon: '📝',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['tools/html-entities', 'word-character-counter', 'text-case-converter'],
    seoTitle: 'Markdown Live Previewer & Editor — GitHub Flavored Markdown | VEYLO',
    seoDescription: 'Write and preview GitHub-flavored Markdown in real time with side-by-side split view, sanitized HTML preview, tables, and code blocks.',
    keywords: ['markdown previewer', 'markdown editor', 'markdown live preview', 'github markdown preview', 'markdown to html'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/diff-checker',
    name: 'Diff Checker — Text & Code Difference Comparator',
    shortDescription: 'Compare two text snippets or code files side-by-side to highlight added, removed, and modified lines in real time.',
    category: 'developer',
    icon: '⚖️',
    status: 'available',
    featured: true,
    popular: true,
    relatedTools: ['json-formatter', 'text-case-converter', 'tools/markdown-preview'],
    seoTitle: 'Diff Checker — Compare Text & Code Differences Online | VEYLO',
    seoDescription: 'Compare two texts, code files, or documents online with split and unified diff views, line numbers, and character-level change highlighting.',
    keywords: ['diff checker', 'text diff tool', 'code diff', 'compare text online', 'file difference checker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/json-yaml',
    name: 'JSON ↔ YAML Converter',
    shortDescription: 'Convert JSON to YAML and YAML to JSON instantly with syntax validation, error highlighting, and indentation controls.',
    category: 'developer',
    icon: '🔄',
    status: 'available',
    popular: true,
    relatedTools: ['json-formatter', 'tools/xml-formatter', 'tools/sql-formatter'],
    seoTitle: 'JSON to YAML & YAML to JSON Converter — Free Online Tool | VEYLO',
    seoDescription: 'Convert between JSON and YAML formats in real time with syntax error validation, custom indentation, and 1-click direction swap.',
    keywords: ['json to yaml', 'yaml to json', 'json yaml converter', 'convert json to yaml online', 'yaml validator'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/jwt-generator',
    name: 'JWT Generator (HMAC-SHA256)',
    shortDescription: 'Generate cryptographically signed JSON Web Tokens (JWT) client-side using Web Crypto API HMAC-SHA256 and custom claims.',
    category: 'developer',
    icon: '🔐',
    status: 'available',
    popular: true,
    relatedTools: ['tools/jwt-decoder', 'hash-generator', 'base64', 'password-generator'],
    seoTitle: 'JWT Generator — Generate Signed JSON Web Tokens Online | VEYLO',
    seoDescription: 'Generate HMAC-SHA256 (HS256) signed JSON Web Tokens client-side with custom payload claims and secret key using Web Crypto API.',
    keywords: ['jwt generator', 'generate jwt token', 'create jwt online', 'hs256 jwt generator', 'sign jwt client side'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/lorem-ipsum',
    name: 'Lorem Ipsum Placeholder Text Generator',
    shortDescription: 'Generate dummy Latin placeholder text for design mockups. Customize paragraphs, sentences, words, and optional HTML markup.',
    category: 'developer',
    icon: '📜',
    status: 'available',
    popular: true,
    relatedTools: ['word-character-counter', 'text-case-converter', 'tools/markdown-preview'],
    seoTitle: 'Lorem Ipsum Generator — Custom Dummy Placeholder Text | VEYLO',
    seoDescription: 'Generate custom Lorem Ipsum dummy text by paragraphs, sentences, or words for design prototypes with instant copy and HTML markup options.',
    keywords: ['lorem ipsum generator', 'dummy text generator', 'placeholder text', 'latin text generator', 'lipsum maker'],
    lastUpdated: '2026-08-29',
  },
  {
    slug: 'tools/user-agent-parser',
    name: 'User-Agent Parser & Device Inspector',
    shortDescription: 'Parse User-Agent strings to inspect browser, version, operating system, device category, and rendering engine.',
    category: 'developer',
    icon: '💻',
    status: 'available',
    popular: true,
    relatedTools: ['tools/url-parser', 'tools/http-status-codes', 'refresh-rate-test'],
    seoTitle: 'User-Agent Parser & Device Inspector — Analyze UA Strings | VEYLO',
    seoDescription: 'Parse and analyze browser User-Agent strings in real time. Detect browser name, version, OS, device type, and rendering engine with 1-click current UA check.',
    keywords: ['user agent parser', 'parse user agent', 'ua parser online', 'user agent lookup', 'browser detection tool'],
    lastUpdated: '2026-08-29',
  },
];

